sudo : required
language: generic

services:
 - docker

before_install:
 - docker build -t luc/docker-react -f Dockerfile .

script:
 - docker run -e CI=true luc/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-eu-central-1-503177946552"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
